name: Archive Repository

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - name: List directory contents
      run: ls

    - name: Achive code
      run: zip -r release.zip .
        
      
    
