name: Archive Repository

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Archive code
       run: zip -r release.zip .


    - name: Achive code
      run: zip -r release.zip .
        
      
    
