name: Archive Repository

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get current directory
      run: pwd
    
    - name: List directory contents
      run: ls -al

    - name: Achive code
      run: zip -r release.zip .
        
      
    
