name: Archive Repository

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Achive code
      run: zip -r release.zip . -i .
        
      
    
