name: 'publish release'
on:
  push:
    tags:
      - '*'
jobs:
  publish_release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v4.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        configuration: "configuration.json"

    - name: Create Release
      id: create_release
      uses: mikepenz/action-gh-release@v0.2.0-a03
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: ${{ steps.github_release.outputs.changelog }}